name: Client CI

on:
  push:
    paths:
      - client/**

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v1
        with:
          node-version: 16.x

      - run: |
          npm ci
          npm run build -w @overstats/client

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v1
        with:
          node-version: 16.x

      - run: |
          npm ci
          npm run lint -w @overstats/client
