name: Server CI

on:
  push:
    paths:
      - server/**

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v1
        with:
          node-version: 16.x

      - run: |
          npm ci
          npm run build -w @overstats/server

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v1
        with:
          node-version: 16.x

      - run: |
          npm ci
          npm run lint -w @overstats/server

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v1
        with:
          node-version: 16.x

      - run: |
          npm ci
          npm run test:cov -w @overstats/server

      - uses: codecov/codecov-action@v1
